### ISSUE TITLE
Emacs formatter results in raw (unreadable) path names in output.

### ISSUE THREAD

**Issue by olliebennett** [ericqweinstein/ruumba#19] opened 2018-08-22 11:47 UTC
I am attempting to integrate `ruumba` into [OverCommit](https://github.com/brigade/overcommit), so we can automatically run `ruumba` on our code as a pre-commit hook, with nice-looking output.

I have discovered that using the `emacs` formatter prevents the output filenames being corrected / displayed correctly (as works fine for other formatters). Output below.

Is there a way to fix this our side?

I am on `ruumba (0.1.5)` and `rubocop (0.58.2)` and my `ruumba.yml` (if relevant) was shared [here](https://github.com/ericqweinstein/ruumba/issues/10#issuecomment-414995291).

Output from `simple` formatter (notice pretty file names):

```
$ bundle exec ruumba --disable-ruby-ext --config .ruumba.yml --format=simple app/views
== app/views/users/download_app.html.erb ==
C: 10: 79: Layout/MultilineArrayBraceLayout: Closing array brace must be on the line after the last array element when opening brace is on a separate line from the first array element.

431 files inspected, 1 offense detected
```

Output from `emacs` formatter (notice ugly file name prefixes):

```
$ bundle exec ruumba --disable-ruby-ext --config .ruumba.yml --format=emacs app/views
/private/var/folders/6x/f21_1m6k4nb652lp1d3_5ldw0000kn/T/d23684922-5977-tt7h84/app/views/users/download_app.html.erb:10:79: C: Layout/MultilineArrayBraceLayout: Closing array brace must be on the line after the last array element when opening brace is on a separate line from the first array element.
```

**Comment by aclemons** [comment] 2018-08-23 02:48
I can't reproduce this. The  [emacs formatter](https://github.com/rubocop-hq/rubocop/blob/v0.58.2/lib/rubocop/formatter/emacs_style_formatter.rb#L17) results in fully-qualified file names, but they match the actual files being linted in my case. 

https://github.com/ericqweinstein/ruumba/blob/fafd6c1076de0c256ee2629c475fe1bbf3ac9174/lib/ruumba/analyzer.rb#L131 and https://github.com/ericqweinstein/ruumba/blob/fafd6c1076de0c256ee2629c475fe1bbf3ac9174/lib/ruumba/analyzer.rb#L151 should cause paths that are fully qualified in the tmp directory to be replaced by the correct paths.

Also tested with ruumba (0.1.5) and rubocop (0.58.2).

```shell
$ bundle exec ruumba --disable-ruby-ext --config .ruumba.yml --format=emacs app/views/
/home/aclemons/dummy/app/views/dummy.html.erb:3:4: C: Style/EmptyElse: Redundant `else`-clause.
```

**Comment by olliebennett** [comment] 2018-08-23 08:02
Awesome, thanks @aclemons - any chance you could share your `.ruumba.yml` config so I can try and find a discrepancy between our configs?

I've tried with my full config (linked above) as well as a basic `.ruumba.yml` file containing only

```yaml
AllCops:
  Include:
    - '**/*.erb'
```

... same result.

I'm on a mac (`10.11.6`) and using `zsh` as my shell in case that makes a difference.

**Comment by aclemons** [comment] 2018-08-23 19:47
I've tested with your minimum config above and also have no problems. I'm on Linux with bash as my shell. I'll check with a colleague who has a mac and see if I can reproduce.

**Comment by aclemons** [comment] 2018-08-23 23:11
My colleague sees the same behaviour as you. We'll attempt to fix and open a PR. Thanks.

**Comment by aclemons** [comment] 2018-08-24 01:44
/tmp is a symlink to /private/tmp on mac. I can reproduce this by setting TMPDIR to a symlink to something else and running ruumba. I've opened a PR with a fix.

**Comment by ericqweinstein** [comment] 2018-09-24 16:57
I'll close this after I review #20. @olliebennett and @aclemons, thanks so much for your patience!

**Closed** 2018-10-11 16:58 UTC
